package com.zenika.airportml.model

/**
  * Created by g.bernonville-ext on 24/04/2017.
  */
case class Flight(Year: String,
                  Month: String,
                  DayofMonth: String,
                  DayOfWeek: String,
                  DepTime: String,
                  CRSDepTime: String,
                  ArrTime: String,
                  CRSArrTime: String,
                  UniqueCarrier: String,
                  FlightNum: String,
                  TailNum: String,
                  ActualElapsedTime: String,
                  CRSElapsedTime: String,
                  AirTime: String,
                  ArrDelay: String,
                  DepDelay: String,
                  Origin: String,
                  Dest: String,
                  Distance: String,
                  TaxiIn: String,
                  TaxiOut: String,
                  Cancelled: String,
                  CancellationCode: String,
                  Diverted: String,
                  CarrierDelay: String,
                  WeatherDelay: String,
                  NASDelay: String,
                  SecurityDelay: String,
                  LateAircraftDelay: String)

object Flight {
  def apply(values: Seq[String]): Flight = new Flight(
    values(0 ),
    values(1 ),
    values(2 ),
    values(3 ),
    values(4 ),
    values(5 ),
    values(6 ),
    values(7 ),
    values(8 ),
    values(9 ),
    values(10),
    values(11),
    values(12),
    values(13),
    values(14),
    values(15),
    values(16),
    values(17),
    values(18),
    values(19),
    values(20),
    values(21),
    values(22),
    values(23),
    values(24),
    values(25),
    values(26),
    values(27),
    values(28))
}